version: '2'
services:
  messenger_bot:
    image: messenger-bot:latest
    build:
      context: .
      dockerfile: ./dockers/rabbitmq/Dockerfile
    container_name: messenger-bot
    hostname: messenger-bot
    restart: 'always'
    ports:
      - 443: 443
    volumes:
      - ./var/log:/var/log
    networks:
      - adcc
networks:
  adcc:
    driver: bridge
